config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :created,
          :accepted,
          :rejected,
          :all
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      #@micropost  = current_user.microposts.build
      #@feed_items = current_user.feed.paginate(page: params[:page])
      #@user_microposts = current_user.microposts.paginate(page: params[:page])

      @user_orders = current_user.orders.paginate(page: params[:page])
    end
  end

  #<!--p>Find me in app/views/users/show.html.erb</p-->
  #    <!--
  #    <% if @user_microposts.any? %>
  #        <h3>Microposts (<%= @user_microposts.count %>)</h3>
  #<ol class="microposts">
  #<%= render @user_microposts %>
  #        </ol>
  #        <%= will_paginate @user_microposts %>
  #                               <% end %>
  #  -->

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<% if find_me? %>
    <p>Find me in app/views/static_pages/about.html.erb</p>
<% end %>

<h1><%= t('About') %></h1>

<p>
<%= t('About message') %>
</p>

<small>
  Разработано с использованием Ruby on Rails
  <a href="http://rubyonrails.org/">http://rubyonrails.org</a>
</small>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% if find_me? %>
    <p>Find me in app/views/static_pages/contact.html.erb</p>
<% end %>
<h1><%= t('Contact') %></h1>

app/views/static_pages/help.html.erb
<% if find_me? %>
    <p>Find me in app/views/static_pages/help.html.erb</p>
<% end %>

<% provide(:title, 'Help') %>
<h1><%= t('Help') %></h1>

<p>
  Ruby on Rails Guides
  <a href="http://guides.rubyonrails.org/">http://guides.rubyonrails.org/</a>.
</p>
<p>
  Перевод Ruby on Rails Guides для версии Rails 4.0
  <a href="http://rusrails.ru/">http://rusrails.ru/</a>.
</p>
<p>
  Ruby on Rails Tutorial
  <a href="http://railstutorial.org/">http://railstutorial.org</a>.
</p>
<p>
  Ruby on Rails Tutorial source
  <a href="https://github.com/railstutorial/sample_app_rails_4">Rails Tutorial source</a>.
</p>
<p>
  Изучение Rails на Примерах
  <a href="http://railstutorial.ru/chapters/4_0/beginning">Ruby on Rails Tutorial</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!--h1>StaticPages#home</h1-->
<!--a href="http://railstutorial.org/">Ruby on Rails Tutorial</a-->
<!--%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %-->

<% if find_me? %>
    <p>Find me in app/views/static_pages/home.html.erb</p>
<% end %>

<!--h1><%= t('Home page') %></h1-->
<!--h2><%= t('Home page') %></h2-->
<h2><%= t('App name') %></h2>
<!--h4><%= t('App name') %></h4-->

<% if signed_in? %>
  <!--div class="row"-->
    <!--aside class="span4"-->
    <!--aside class="span4"-->
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <!--%= render 'shared/stats' %-->
      </section>
      <section>
        <!--%= render 'shared/micropost_form' %-->
      </section>
    <!--/aside-->
    <!--div class="span8"-->

    <!--%= link_to 'Создать заявку', new_order_path %-->
    <!--%= link_to 'Создать заявку', new_order_path, class: "btn btn-large btn-primary" %-->
    <br>
    <% if !current_user.reader%>
        <%= link_to 'Создать заявку', new_order_path, class: "btn btn-large btn-primary" %>
    <% end %>
    <br>
    <br>

    <div>
      <h3>Список заявок</h3>
      <!--%= render 'shared/feed' %-->
      <% if @user_orders.any? %>
          <!--h3>user_orders (<%= @user_orders.count %>)</h3-->
          <%= will_paginate @user_orders %>
          <ol class="orders">
            <%= render @user_orders %>
          </ol>
          <%= will_paginate @user_orders %>
      <% end %>
    </div>

  <!--/div-->
<% else %>
  <div class="center hero-unit">
    <h4><%= t('start_message_1') %></h4>

    <%= link_to t('Sign in'), signin_path,
                class: "btn btn-large btn-primary" %>
  </div>
  <div hidden class="center hero-unit">
    <h4><%= t('start_message_2') %></h4>
    <%= link_to t('Sign up'), signup_path%>
  </div>
<% end %>