config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :created,
          :accepted,
          :rejected,
          :all
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if find_me? %>
    <p>Find me in app/views/shared/_error_messages.html.erb</p>
<% end %>

<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_feed.html" %>

<%# if @feed_items.any? %>
<% if !@feed_items.nil? %>
  <%= will_paginate @feed_items %>  
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>  
  <%= will_paginate @feed_items %>  
<% end %>

app/views/shared/_feed_item.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_feed_item.html" %>

<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_micropost_form.html" %>

<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <!--%= f.text_area :content, value: "new micropost!" %-->
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% if find_me? %>
    <p>Find me in app/views/shared/_stats.html.erb</p>
<% end %>

<!--Партиал для отображения статистики-->

<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_error_messages.html.erb
<% if find_me? %>
    <p>Find me in app/views/shared/_user_error_messages.html.erb</p>
<% end %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>
<% if find_me? %>
    <p>Find me in app/views/shared/_user_info.html.erb</p>
<% end %>

<!--%= link_to gravatar_for(current_user, size: 52), current_user %-->
<% @user ||= current_user %>

<h3>
  <%= "Данные оператора" %>
</h3>

<p>
  <strong>Оператор:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if current_user?(@user)%>
    <p>
      <strong>Профиль:</strong>
      <!--%= link_to "Посмотреть профиль", current_user %-->
      <%= link_to "Редактировать профиль", edit_user_path(@user) %>
    </p>
<% end %>

<p>
  <strong>Создано заявок:</strong>
  <%= @user.orders.count %>
</p>

<p>
  <strong>Права пользователя:</strong>
</p>
<p>
  <strong>Активирован:</strong>
  <%= @user.active %>
</p>
<p>
  <strong>Проверяющий:</strong>
  <%= @user.reader %>
</p>
<p>
  <strong>Администратор:</strong>
  <%= @user.admin %>
</p>





<span>
  <!--%= pluralize(current_user.microposts.count, "micropost") %-->
</span>

app/views/shared/_user_info_v0.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>
<% if find_me? %>
    <p>Find me in app/views/shared/_user_info.html.erb</p>
<% end %>

<!--%= link_to gravatar_for(current_user, size: 52), current_user %-->

<h3>
  <%= "Данные оператора" %>
</h3>

<p>
  <strong>Оператор:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>email:</strong>
  <%= current_user.email %>
</p>

<p>
  <strong>current_user.reader:</strong>
  <%= current_user.reader %>
</p>
<p>
  <strong>current_user.admin:</strong>
  <%= current_user.admin %>
</p>

<p>
  <strong>Профиль:</strong>
  <!--%= link_to "Посмотреть профиль", current_user %-->
  <%= link_to "Редактировать профиль", edit_user_path(current_user) %>
</p>

<p>
  <strong>Создано заявок:</strong>
  <%= current_user.orders.count %>
</p>



<span>
  <!--%= pluralize(current_user.microposts.count, "micropost") %-->
</span>