config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :created,
          :accepted,
          :rejected,
          :all
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  
  
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<!--li><a href="http://news.railstutorial.org/">News</a></li-->
<!--a href="http://railstutorial.org/">Rails Tutorial</a-->

<footer class="footer">
  <!--small>
    Разработано с использованием Ruby on Rails
    <a href="http://rubyonrails.org/">http://rubyonrails.org</a>
  </small-->
  <nav>
    <ul>
      <!--li><%= link_to t('Help'),    help_path %></li-->
      <li><%= link_to t('About'),   about_path %></li>
      <!--li><%= link_to t('Contact'), contact_path %></li-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <!--%= link_to t('App name'), root_path, id: "logo" %-->
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to t('Home'), root_path %></li>

          <% if signed_in? %>
            <li><%= link_to t('Users'), users_path %></li>
            <!--li><!--%= link_to t('Orders'), orders_path %></li-->

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%=t('Orders')%> <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to 'Список заявок', orders_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Новые', created_orders_path %></li>
                  <li><%= link_to 'Принятые', accepted_orders_path %></li>
                  <li><%= link_to 'Отклоненные', rejected_orders_path %></li>
                  <li><%= link_to 'Все заявки', all_orders_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Создать заявку', new_order_path %></li>
                </ul>
              </li>


            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%=t('Account')%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('Profile'), current_user %></li>
                <li class="divider"></li>
                <li><%= link_to t('Settings'), edit_user_path(current_user) %></li>
              </ul>
            </li>

            <li>
              <%= link_to t('Sign out'), signout_path, method: "delete" %>
            </li>            
          <% else %>
            <li><%= link_to t('Sign in'), signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
<!-- 		            
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>        
--> 
      <%= yield %>
    </div>
    <div class="container">
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>